### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by vishvananda** [viraptor/prctl-rs#2]
Hello, I'm attempting to use this library for a project, but it is missing licensing information. Most of the rust ecosystem is dual APACHE/MIT Could you add LICENSE-APACHE and LICENSE-MIT to the top level of the source? Also you could add something like the following to your readme:

```
## License

Licensed under either of

 * Apache License, Version 2.0, ([LICENSE-APACHE](LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)

at your option.
```

**Comment by viraptor** [comment]
MIT was already marked in the Cargo.toml, but I added the license file as well.
Thanks for checking!
